version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - redis
    tty: true
    ports:
      - 3000:3000
  redis:
    build: ./containers/redis
    tty: true
    ports:
      - 6379:6379
  rethinkdb:
    build: ./containers/rethinkdb
    tty: true
    ports:
      - 8080:8080
      - 28015:28015
